language: java
jdk:
  - openjdk7

env:
  - ES_TEST_LOCAL=true
  - ES_TEST_LOCAL=false

notifications:
  email: false
after_success:
  - bash <(curl -s https://copilot.blackducksoftware.com/ci/travis/scripts/upload)
